### PR TITLE
Support Django 2.0

### PR DESCRIPTION
**Pull request by mthpower**
Update to support Django 2.0

I've run the tests on 
- django 1.8 - failed `AttributeError: module 'django.db.transaction' has no attribute 'on_commit'` I think that was introduced by #6 
- django 1.9 - passed
- django 1.11 - passed
- django 2.0 - passed

For Django 2.0 compatibility I had to 
- update the middleware so that the parent class  `__init__` is called.

- https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0
details that `remote_field.to` has been removed. `model` is now the attribute to use.

### CODE REVIEW

**Comment by lamby** [comment]
Awesome, released as `1.0.0` (drops 1.8 support hence major version bump)!

**Comment by mthpower** [comment]
thanks!
